### ISSUE TITLE
Move Alignment with the 1+MG Trust Framework

### ISSUE THREAD

**Issue by MKonopkoELIXIR** [elixir-europe/human-data-maturity-model#6]
The indicator "Alignment with the 1+MG Trust Framework" needs to be moved to Organisation: Alignment with Initiatives and placed below the "1+MG national mirror group alignment" indicator.  This would then get rid of the "Trust & Transparency" subdomain.

Could you please help with this, @martin-nc?  I can't seem to do it without messing up the structure.

**Comment by martin-nc** [comment]
@MKonopkoELIXIR Can you check now?

HTML table refresher, in case it's handy in future: the "Alignment with the 1+MG Trust Framework" row contained four columns. Getting rid of the first column ("Trust & Transparency") means you now have three columns in the row. You put the row under "Alignment with initiatives" and that's okay because it has the same number of columns as the other entries in that section (i.e. three) **but** you have to increase the rows the "Alignment with initiatives" cell covers, so `<td rowspan="5">Alignment with initiatives</td>` (rather than `rowspan="4"`). Maybe that's where you went wrong.

**Comment by MKonopkoELIXIR** [comment]
Thanks for the refresher (very helpful!) and for fixing the indicator for me.
